<template>
  <v-layout>
    <v-layout
      column
      justify-center
      align-center
    >
      <v-flex
        xs12
        sm8
        md6
        class="text-center"
      >
        <h1>Clips</h1>
        <h2>Coming soon!</h2>
      </v-flex>
    </v-layout>
  </v-layout>
</template>
