name: CI
on: push
env:
  GHR_TOKEN: ${{ secrets.GHR_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Units tests
      run: yarn test:unit:ci